export type IconName =
  | 'chevron-down'
  | 'chevron-right'
  | 'chevron-left'
  | 'chevron-up'
  | 'arrow-left'
  | 'arrow-right'
  | 'account'
  | 'clipboard-text'
  | 'shield-remove'
  | 'lock'
  | 'plus'
  | 'baseline-dashboard'
  | 'chart-pie'
  | 'file-invoice-dollar'
  | 'baseline-assignment'
  | 'round-assignment-turned-in'
  | 'calculator-variant'
  | 'sharp-settings'
  | 'close'
  | 'refresh'
  | 'trash'
  | 'file-document'
  | 'check'
  | 'clock'
  | 'info'
  | 'edit'
  | 'warning'
  | 'baseline-filter-list'
  | 'upload'
  | 'download'
  | 'alert'
  | 'check-circle'
  | 'calendar'
  | 'outline-info'
  | 'fullscreen'
  | 'camera'
  | 'baseline-add-circle'
  | 'octagon-warning'
  | 'baseline-person'
  | 'calendar-blank-outline'
  | 'search'
  | 'eye'
  | 'eye-off'
  | 'tray-upload'
  | 'menu-open'
  | 'home'
  | 'handshake'
  | 'file-document-check'
  | 'credit-card-check'
  | 'database'
  | 'menu-close';

export interface NIconProps {
  name?: IconName;
  class?: any;
  size?: number | string;
}
